version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src/docker/nginx:/etc/nginx/conf.d
            - ./public:/var/app
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
        links:
            - php
    php:
        build:
            context: docker/php
        volumes:
            - .:/var/app